---
title: "NDBI048 - `GeoData` - EDA"
author: "Michal Pospěch"
execute:
  echo: false
jupyter: python3
---

# Introduction
This document analyses data from the "Geodata" dataset. As the dataset is somewhat large, only its subset regarding election results and sociodemographic indicators will be analysed and used further with focus on modeling election results from 
 - past parlimentary election results and
 - sociodemographic data.

# Dataset
This dataset contains election-district level sociodemographic data and election results. Fortunately the dataset is complete and contains no duplicities in data thus no cleaning has to be done. 
The dataset contains 14271 rows and 51 columns, each row representing one electoral district.

```{python}
import scripts
%matplotlib inline
import matplotlib_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg')
df = scripts.load_extended_dataset("./data/volby/dataset_extended.csv")

```
## Columns 
Meaning of each column is described in the provided file and is as follows:

 - `obec_okrsek` - district and municipality code, is unique and is used as index
 - `obec` - municipality (LAU2) code
 - `okres` - county (LAU1)
 - `kraj` - region (NUTS3)
 - `vel.obce` - number of inhabitants
 - `par{21,17}vsezn` - Parlimentary elections 2021/17, number of votes from the "electoral list"
 - `par{21,17}phcelkem` - Parlimentary elections 2021/17, number of votes in district
 - `par{21,17}*` - Parlimentary elections 2021/17, number of votes for a particular party
 - `prez18zem2` - Presidential elections 2018, 2nd round, number of votes for M. Zeman
 - `prez18dra2` - Presidential elections 2018, 2nd round, number of votes for J. Drahos
 - `nazev_obce` - municipality name
 - `nazev.pha` - city name (same as `nazev_obce` for non-statutary cities)
 - `sl11obyvatel` - Census 2011, number of inhabitants 
 - `sl11muzi` - Census 2011, number of men
 - `sl11rozv` - Census 2011, divorced
 - `sl11deti` - Census 2011, children
 - `sl11seni` - Census 2011, pensioners
 - `sl11kat` - Census 2011, catholics
 - `sl11rom` - Census 2011, roma
 - `sl11vs` - Census 2011, university education
 - `sl11vos` - Census 2011, vocational school
 - `sl11nast` - Census 2011, extended high school
 - `sl11strm` - Census 2011, high school with maturita
 - `sl11strb` - Census 2011, high school without maturita
 - `sl11zakl` - Census 2011, elementary school
 - `sl11zam` - Census 2011, employed
 - `sl11pod` - Census 2011, enterpreneur
 - `sl11nezam` - Census 2011, unemployed
 - `sl11neprduch` - Census 2011, non-working pensioners (retired)
 - `sl11budov` - Census 2011, number of buildings

## Feature Extraction

Unfortunately all the values are absolute meaning that any model applied to the dataset would predict that in big districs parties tend to get more votes. Thus transforming all the values to ratios of total population in the district was needed. Also number of women was not provided and had to be calculated as `total` - `men`.

## Exploration

We start with exploring the various sociodemogaphic indicators provided. 
```{python}
scripts.plot_gender_counts(df)

```
The total number of inhabitants described in the dataset is 9884171 with numbers of men and women being roughly equal.
```{python}
scripts.plot_municipality_size_ratio(df)

```
One of the factors that could be influencing political preferences of people is the size of the municipality they live in. Close to 25% of people live in a small town.

```{python}
scripts.plot_edu_count(df)

```
Another factor influencing electoral behaviour could be the level of education. More than 50% of the population have high school education while just over 10% have a university degree.

```{python}
  scripts.plot_other_sociodem(df)

```
It can be clearly seen that the population of Roma people is really low. In addition children and pensioners make more than 30% of the population.
```{python}
scripts.plot_elections_2017(df)
```
In 2017 ANO won the elections by a huge margin and 9 parties got more than 5% of votes and got into the Chamber of Deputies.

```{python}
scripts.plot_elections_2021(df)
```
In 2021 ANO won the elections as well, however with much smaller margin only 4 parties (and coallitions) got into the Chamber of Deputies.

### Relationships
To understand election results better let's explore how they relate to other variables.
First, let's explore how does size of municipality influence election results.

```{python}
scripts.elections2017_size_plot(df)

```



```{python}
scripts.elections2021_size_plot(df)

```

Clearly ANO, SPD and KSCM do not do well in big cities (such as Prague) while ODS, Pirati and TOP09 (and SPOLU and PirSTAN for that matter) doing disproportionately well in bigger cities.

To gain more insight into this result, let's see how does size of municipality relate to education and employment distribution.
```{python}
scripts.plot_employment_size(df)
```
Clearly, the distribution of employment does not vary very much between different sizes of municipalities.
```{python}

scripts.education_size_plot(df)
```
 
Education varies heavily based on municipality size with university-educated people making up almost 20% of inhabitants of big cities while making up less than 5% of small village population.

Now, let's explore how are other sociodemographic indicators connected with election results. To get insight into the relationships we will use Paerson correlation coefficients between election results and sociodemographic data. The correlation data is presented in tables below and correlations of interest are pointed out.The trends from previous election are mostly reinforced, ANO has positive correlation with low education, unemployed and retired, same as SPD, SPOLU (ODS + TOP09 + KDU) with high education, employees and the self-employed.



First we explore the 2017 elections.

```{python}
scripts.correlations_2017(df)
```
Clearly ANO's support is negatively correlated with higher education and income (employees and enterpreneurs) and positively with lower education and having income from the state (pensioners and unemployed).

ODS has an inverse correlation profile to ANO. Its support is positively correlated with higher education and being employed or self-employed.

Piráti are similar to ODS, they have extremely high positive correlation with higher education .

KDU has extremely high correlation with catholics which is to be expected given their name. It also has negative correlation with divorced which is to be expected as well. 

SPD has strong negative correlation with higher education, and positive correlation with lower education and the unemployed.

ČSSD has strong positive correlations with unemployed, retired and pensioners and slightly weaker with lower education.

TOP09 has similar correlations as the Piráti do.

STAN has no strong correlations.

KSČM is similar to SPD and ANO, high positive correlation with lower education, unemployed and pensioners.

---

Now let's continue with 2021

```{python}
scripts.correlations_2021(df)
```

The trends from previous election are mostly reinforced, ANO has positive correlation with low education, unemployed and retired, same as SPD, SPOLU (ODS + TOP09 + KDU) with high education, employees and the self-employed.

PirSTAN is similar in the correlation profile to SPOLU, most significant difference is the correlation with catholics where SPOLU has not an insignificant positive correlation, most likely due to KDU being part of SPOLU and PirSTAN has strong negative correlation.

Other things to note are the correlations with Roma population, it's strongest with Zelení and PirSTAN,